#!/usr/bin/env python3
"""
FreeCAD Adapter for Geometry Interpreter
Provides unified interface to FreeCAD CAD engine
"""

import sys
import json
from pathlib import Path
from typing import Dict, List, Any, Optional

# Import FreeCAD modules
try:
    import FreeCAD
    import Part
    import Mesh
    FREECAD_AVAILABLE = True
except ImportError:
    FREECAD_AVAILABLE = False
    print("Warning: FreeCAD not available", file=sys.stderr)


class FreeCADAdapter:
    """Adapter for FreeCAD CAD engine"""
    
    def __init__(self):
        """Initialize FreeCAD adapter"""
        self.doc = None
        self.available = FREECAD_AVAILABLE
        
        if not self.available:
            print("[FreeCAD] Module not available - will generate placeholders", file=sys.stderr)
    
    def generate_geometry(self, design_data: Dict[str, Any], 
                         build_id: str, output_dir: Path) -> Dict[str, Any]:
        """
        Generate geometry using existing FreeCAD generator
        
        Args:
            design_data: Design instructions
            build_id: Build identifier
            output_dir: Output directory
            
        Returns:
            Result dict with files and metadata
        """
        # Import the main FreeCAD generator
        script_dir = Path(__file__).resolve().parent
        sys.path.insert(0, str(script_dir.parent / 'cad'))
        
        from freecad_generator import generate_cad_model
        
        files = generate_cad_model(design_data, output_dir, build_id)
        
        return {
            'success': True,
            'files': files,
            'engine': 'freecad',
            'build_id': build_id
        }
    
    def execute_operations(self, design_data: Dict[str, Any], 
                          build_id: str, output_dir: Path) -> Dict[str, Any]:
        """
        Execute design language operations
        
        Args:
            design_data: Design with operations array
            build_id: Build identifier
            output_dir: Output directory
            
        Returns:
            Result dict with files and metadata
        """
        # Import design language executor
        script_dir = Path(__file__).resolve().parent
        sys.path.insert(0, str(script_dir.parent / 'cad'))
        
        from design_language import execute_design_language
        
        files = execute_design_language(design_data, build_id, output_dir)
        
        return {
            'success': True,
            'files': files,
            'engine': 'freecad',
            'design_language': True,
            'build_id': build_id
        }
    
    def export_geometry(self, geometry: Any, output_path: Path, format: str) -> bool:
        """
        Export geometry to file
        
        Args:
            geometry: FreeCAD Part object
            output_path: Output file path
            format: Export format (stl, step, obj, etc.)
            
        Returns:
            True if successful
        """
        if not self.available:
            return False
        
        format = format.lower()
        
        try:
            if format == 'step':
                geometry.exportStep(str(output_path))
            elif format == 'stl':
                mesh = Mesh.Mesh()
                mesh.addFacets(geometry.tessellate(0.1))
                mesh.write(str(output_path))
            elif format == 'obj':
                mesh = Mesh.Mesh()
                mesh.addFacets(geometry.tessellate(0.1))
                # OBJ export
                self._export_obj(mesh, output_path)
            elif format == 'iges':
                geometry.exportIges(str(output_path))
            elif format == 'brep':
                geometry.exportBrep(str(output_path))
            else:
                raise ValueError(f"Unsupported format: {format}")
            
            return True
        except Exception as e:
            print(f"[FreeCAD] Export failed: {e}", file=sys.stderr)
            return False
    
    def _export_obj(self, mesh, output_path: Path):
        """
        Export mesh to OBJ format (for visualization)
        
        Args:
            mesh: FreeCAD Mesh object
            output_path: Output file path
        """
        with open(output_path, 'w') as f:
            f.write("# OBJ file generated by Product Builder\n")
            f.write(f"# Vertices: {len(mesh.Topology[0])}\n")
            f.write(f"# Faces: {len(mesh.Topology[1])}\n\n")
            
            # Write vertices
            for vertex in mesh.Topology[0]:
                f.write(f"v {vertex[0]} {vertex[1]} {vertex[2]}\n")
            
            # Write faces (1-indexed)
            for face in mesh.Topology[1]:
                f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")
    
    def create_document(self, name: str = "Design"):
        """Create a new FreeCAD document"""
        if self.available:
            self.doc = FreeCAD.newDocument(name)
            return self.doc
        return None
    
    def close_document(self):
        """Close the current document"""
        if self.doc and self.available:
            FreeCAD.closeDocument(self.doc.Name)
            self.doc = None
